### ISSUE TITLE
Add an event to indicate a reorder was actually performed

### ISSUE THREAD

**Issue by gdurandrexel** [igorkurilenko/animated_reorderable#3]
When the user drags an item to reorder, I'd like to update the server with the new order only if the order was actually changed.

Currently I use onItemDragEnd but it is triggered even if the item stayed at its position. I could compare the states before and after the drag to detect an update, but I think this use case is common enough that it may deserve an easier API, e.g. a onReorderEnd callback.

**Comment by igorkurilenko** [comment]
Could you provide more details on the context of what you're trying to achieve?

Because you're responsible for the actual reordering, and this is done using this callback:

`
// the order actually changes here
onReorder: (permutations) => permutations.apply(items),
`

Maybe you need callbacks for the completion of the reorder animation?

**Comment by gdurandrexel** [comment]
The onReorder callback allows to update the UI, but, when the user is done moving an item, I need to store the new item order on the server.
I would like a callback when the user actually releases the item in its new position. Currently, onItemDragEnd does the "released" part but it is triggered even when the position did not change. I'd like a callback that is called when the item is released in a **new** position. It's for convenience, I could compute that, but it would be nice if it would be integrated in the API.

**Comment by igorkurilenko** [comment]
The actual permutation occurs when the permutations.apply(items) method is called. I can make the Permutations class iterable so that it is possible to track which indices are being changed. This way, updates can be sent to the server. Would this approach be convenient?

**Comment by igorkurilenko** [comment]
> The onReorder callback allows to update the UI, but, when the user is done moving an item, I need to store the new item order on the server. I would like a callback when the user actually releases the item in its new position. Currently, onItemDragEnd does the "released" part but it is triggered even when the position did not change. I'd like a callback that is called when the item is released in a **new** position. It's for convenience, I could compute that, but it would be nice if it would be integrated in the API.

It is not possible within the current design to quickly implement the onReorderEnd solution in such a way that an argument with the history of all permutations is passed. Currently, onReorder(permutations) can be called multiple times within a single reorder session, depending on how many positions the item was dragged. At the same time, the permutations entity will contain a collection of permutations each time.

**Comment by gdurandrexel** [comment]
I do not want to know which permutations happened. I just want to know when the drag ended with an actual change in the position of the dragged item (maybe the new index of the item would be nice as an argument for some use cases).

In my case I actually send to the server the order of all the items, which I track using onReorder in which I apply the permutations to this list. I could store the state of the list before drag and compare it with its new state in onItemDragEnd to determine if there was an actual change in position that need storing on the server, but I hoped the lib could do this for me.

If it is not possible, it is no big deal: it is just a convenience event.

**Comment by igorkurilenko** [comment]
I just made Permutations iterable and made the Permutation class public. Now you can get the indices like this:
```dart
onReorder: (permutations) {
    permutations.apply(items);
    for(final permutation in permutations) {
      print('permutation: from index ${permutation.from} to index: ${permutation.to}');
    }
}
```

Will this approach help for the time being?

**Comment by gdurandrexel** [comment]
No sorry. I'd like a distinct event as described above: `void Function() onReorderEnd`, triggered at the exact same time as onItemDragEnd but only if the position of the dragged item was actually modified.

**Comment by igorkurilenko** [comment]
Is the onReorderEnd implementation in [ReorderableListVIew](https://api.flutter.dev/flutter/material/ReorderableListView-class.html) the method that you need? Can I use it as a guide for implementation?

**Comment by gdurandrexel** [comment]
you mean the signature with `(int oldIndex, int newIndex)`? Yes a callback like this would work. I could simply test oldIndex != newIndex to determine whether I should update on the server.
Though, in my case, I don't really care about the indexes: I just need to know whether they are different. But other uers might find that useful.

**Comment by igorkurilenko** [comment]
I tried to design the API as closely as possible to ReorderableListView. It has an onReorderEnd method, which is triggered even if there was no actual change in the order of items. 

You can track the fact of order changes and get the indices using the onReorder method, while the onItemDragEnd method can be used to know when an item was dropped.

It’s very difficult to implement  in `(int oldIndex, int newIndex)` style because I have a feature that disables reordering for certain items.

**Comment by gdurandrexel** [comment]
I feel stupid: I hadn't realized that the index in onItemDragEnd was the index at the dropped location...
It's pretty straightforward then to detect a change: store the index in onItemDragStart and compare it to the one in onItemDragEnd and then save if needed.

```dart
onItemDragStart: (_, index) {
  _dragStartIndex = index;
},
onItemDragEnd: (_, index) {
  if (_dragStartIndex != index) {
    _save();
  }
},
```

Sorry for this long useless conversation.

A suggestion though: you may want to emphasize in the doc of onItemDragEnd that the index is the position where the item is dropped. Currently the description of index is the same in onItemDragStart and onItemDragEnd .

**Comment by igorkurilenko** [comment]
https://github.com/igorkurilenko/animated_reorderable/commit/d5fda91b3484f850ac561d2b55a0714a93a7be0d

This conversation has been very helpful for the development of the project. Thank you for your willingness to improve animated_reorderable.
